<?php

/**
 * Created by PhpStorm.
 * User: adamin90
 * Date: 2017/6/27
 * Time: 9:41
 */
class NeworderAction extends  NewbaseAction
{
    private  $uid;
    private $userCard;  //购物车model
    private  $groupModel; //group model


    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stubud
        $this->uid=$_REQUEST["uid"];
        $this->userCard=D("Usercard");//购物车表
        $this->groupModel=D("Group");//商品表
    }


    /**
     * 填写订单  需要 uid  token   addressid
     */
    public function writeorder()
    {   $now=$_SERVER["REQUEST_TIME"];
        $useradress = D("User_adress");
        $addressid = $_GET["addressid"];

        $nowaddress = array("noadress"=>1);
        if (empty($addressid)) {
            $address1 = $useradress->get_one_adress($this->uid);
            if (!empty($address1)) {
                $nowaddress = $address1;
            }
        } else {
            $address = $useradress->get_one_adress($this->uid, $addressid);
            if (!empty($address)) {
                $nowaddress = $address;
            }
        }

        if($nowaddress["noadress"]){

        }else{
            if(empty($nowaddress["province_txt"])){
                $nowaddress["province_txt"]="";
                $nowaddress["city_txt"]="";
                $nowaddress["area_txt"]="";

            }
        }

  //    echo   gettype();
    //    die;

        $cards = $this->userCard->where("uid = " . $this->uid . " AND selected = 1 ")->order("add_time ASC ")->select();
        $total=0;
        if (empty($cards)) {
            $this->returnAjax("购物车数据为空", 2);
        } else {
            $groupimage = new group_image();

            foreach ($cards as $key => $value) {
                $group = $this->groupModel->where("group_id = " . $value["group_id"] . " AND begin_time < " . time() . " AND end_time > " . time() . " AND status = 1 AND is_group_buy = 0 ")->find();
                if (empty($group)) {
                    $this->userCard->where("group_id = " . $value["group_id"])->delete();  //删除过期数据
                    unset($cards[$key]);
                } else {
                    $cards[$key]["mer_id"] = $group["mer_id"];
                    $cards[$key]["title"] = $group["s_name"];
                    $cards[$key]['image'] = $groupimage->get_allImage_by_path($group["pic"], s)[0];
                    $cards[$key]['price'] = $group['price'];
                    $total+=(round(floatval($group['price'])*intval($value['pro_num']),2));


                }
}



}
        $result['adressinfo']=$nowaddress;
        $result['cards']=$cards;
        $result["total_money"]=$total;
        $couponcondition=" uid =".$this->uid." AND starttime <".$now." AND endtime > ".$now." AND ranges <= ".$total." AND comfirmed = 0";
        $coupons=D("Usercoupon")->where($couponcondition)->select();
        foreach ($coupons as $key=>$value){
            if($value["endtime"]<$now){
                $coupons[$key]["comfirmed"]=2;
            }
            if($value["type"]==1){
                $coupons[$key]['desc']="新人红包";
                if($value["ranges"]<=0){
                    $coupons[$key]["shortdesc"]="立减".$value["denomination"]."元";
                    $coupons[$key]["longdesc"]="新人下单无门槛立减".$value["denomination"]."元";
                }else{
                    $coupons[$key]["shortdesc"]="立减".$value["denomination"]."元";
                    $coupons[$key]["longdesc"]="新人下单"."满".$value["ranges"]."立减".$value["denomination"]."元";
                }
            }elseif ($value["type"]==2){
                $coupons[$key]["desc"]="普通红包";
                if($value["ranges"]<=0){
                    $coupons[$key]["shortdesc"]="立减".$value["denomination"]."元";
                    $coupons[$key]["longdesc"]="下单无门槛立减".$value["denomination"]."元";
                }else{
                    $coupons[$key]["shortdesc"]="满".$value["ranges"]."立减".$value["denomination"]."元";
                    $coupons[$key]["longdesc"]="下单满".$value["ranges"]."立减".$value["denomination"]."元";
                }
            }
        }

        if(empty($coupons)){
            $result["coupons"]=array();
        }else{
            $result["coupons"]=$coupons;
        }
        $this->returnAjax($result,1);
    }

    /**
     * 列出购物车可用红包
     */
    public function listcardcoupons()
    {
        $now=$_SERVER["REQUEST_TIME"];
        $cards = $this->userCard->where("uid = " . $this->uid . " AND selected = 1 ")->order("add_time ASC ")->select();
        $total = 0;
        if (empty($cards)) {
            $this->returnAjax("购物车数据为空", 2);
        } else {
            $groupimage = new group_image();

            foreach ($cards as $key => $value) {
                $group = $this->groupModel->where("group_id = " . $value["group_id"] . " AND begin_time < " . time() . " AND end_time > " . time() . " AND status = 1 AND is_group_buy = 0 ")->find();
                if (empty($group)) {
                    $this->userCard->where("group_id = " . $value["group_id"])->delete();  //删除过期数据
                    unset($cards[$key]);
                } else {

                    $total += (round(floatval($group['price']) * intval($value['pro_num']), 2));


                }
            }


        }

        $couponcondition=" uid =".$this->uid." AND starttime <".$now." AND endtime > ".$now." AND ranges <= ".$total." AND comfirmed = 0";
        $coupons=D("Usercoupon")->where($couponcondition)->select();
        foreach ($coupons as $key=>$value){
            if($value["endtime"]<$now){
                $coupons[$key]["comfirmed"]=2;
            }
            if($value["type"]==1){
                $coupons[$key]['desc']="新人红包";
                if($value["ranges"]<=0){
                    $coupons[$key]["shortdesc"]="立减".$value["denomination"]."元";
                    $coupons[$key]["longdesc"]="新人下单无门槛立减".$value["denomination"]."元";
                }else{
                    $coupons[$key]["shortdesc"]="立减".$value["denomination"]."元";
                    $coupons[$key]["longdesc"]="新人下单"."满".$value["ranges"]."立减".$value["denomination"]."元";
                }
            }elseif ($value["type"]==2){
                $coupons[$key]["desc"]="普通红包";
                if($value["ranges"]<=0){
                    $coupons[$key]["shortdesc"]="立减".$value["denomination"]."元";
                    $coupons[$key]["longdesc"]="下单无门槛立减".$value["denomination"]."元";
                }else{
                    $coupons[$key]["shortdesc"]="满".$value["ranges"]."立减".$value["denomination"]."元";
                    $coupons[$key]["longdesc"]="下单满".$value["ranges"]."立减".$value["denomination"]."元";
                }
            }
        }
     if(!empty($coupons)){
         $this->returnAjax($coupons,1);
     }else{
         $this->returnAjax("您没有符合条件的红包",2);
     }
    }

    /**
     * 提交购物车订单
     * @param int $_POST["addressid"] 会员的地址id
     * @param     $_POST["couponid"]  会员的优惠券id
     * @table Usercoupon 会员优惠券表
     * @table userCard 会员购物车表
     */
    public function  submitcardorder(){
        if(IS_POST)
            //传进用户的地址id,因为一个人会设有多个地址,所以有多个地址id
            $addressid=$_POST["addressid"];
            //查找地址,如果查不到,则返回错误
            $addressinfo=D("User_adress")->where("adress_id = ".$addressid." AND uid = ".$this->uid)->find();
            if(empty($addressinfo)){
                $this->returnAjax("非法地址请求",0);
            }else{
                $couponid=$_POST["couponid"];
                //判断是否用了优惠券
                if(!empty($couponid)){   //用户优惠券表                                          //确认的       //优惠券时间小于现在的时间                        优惠券的终止时间大于现在时间                 传进来的优惠券id
                    $usercoupon=D("Usercoupon")->where("uid =".$this->uid." AND comfirmed =0 AND starttime <".$_SERVER["REQUEST_TIME"]." AND endtime> ".$_SERVER["REQUEST_TIME"]." AND id =".$couponid)->find();
                    if(empty($usercoupon)){
                        //如果没有查询到红包则返回不存在的红包
                        $this->returnAjax("不存在的红包",0);
                    }
                }
                 //如果查到用户有优惠券,则将收货地址和优惠券信息传进添加订单方法,如果没有则传0,0为无优惠原价下单
                 if(!empty($usercoupon)){
                     $orderinfo=$this->submitorderaction($addressid,$usercoupon);
                 }else{
                     $orderinfo=$this->submitorderaction($addressid,0);
                 }
                //如果返回的是false则取反为true,执行返回失败。当执行true时，则执行成功
                if(!$orderinfo){
                    $this->returnAjax("提交购物车订单失败",0);
                }else{
                    //如果当提交订单成功，则删除购物车里的商品，当失败时，返回购物车删除失败。否则返回成功
                    if(!($this->userCard->where("uid = ".$this->uid." AND selected = 1")->delete())){
                        $this->returnAjax("提交购物车订单成功，但删除购物车选中订单失败",0);
                    }
                    $this->returnAjax($orderinfo,1);
                }

            }

        }else{
            //如果不是post传过来返回非法
            $this->returnAjax("非法请求",0);
        }

    }

    /**
     * @param int $addressid 会员收货地址
     * @param int $coupon 会员优惠券id
     * @return array|bool
     * 提交购物车订单   返回购物车订单id  删除购物车选中订单
     */
    private function submitorderaction($addressid,$coupon=0){
      //  echo  round(0.01,2);
        //给用户订单加随机标识
        $adamid=create_uuid("adam");
        //用户购物车表提交的数据传进变量
        $usercards=D("Usercard")->where("uid = ".$this->uid." AND selected = 1 ")->select();
        if(empty($usercards)){
            return false;
        }
        //查找用户收货地址id
        $addressinfo=D("User_adress")->where("adress_id = ".$addressid)->find();
        if(empty($addressinfo)){
            return false;
        }

        //地区表.三级联动,将地址的id查出来,返回该条信息的area_name
        $areadata=D("Area");
        $adrprovince=$areadata->where("area_id = ".$addressinfo['province'])->find()['area_name'];
        $adrcity=$areadata->where("area_id = ".$addressinfo['city'])->find()['area_name'];
        $adrarea=$areadata->where("area_id = ".$addressinfo['area'])->find()['area_name'];
        //订单表
        $group_orderdata=D("Group_order");
        //查询商品表,找到用户提交的商品,并遍历
        foreach ($usercards as $key=>$value){
            $groupnow=$this->groupModel->where("group_id = ".$value["group_id"])->find();
            //判断是否查到商品
            if(empty($groupnow)){
                return false;
            }

        }
        $moneysum=0;   //总钱数
        //团购对应店铺
        $groupstore=D('Group_store');
        //遍历购物车里的订单
        foreach ($usercards as $key=>$value){
            //查到商品信息
            $groupnow=$this->groupModel->where("group_id = ".$value["group_id"])->find();
            if(!empty($Group_store) && (count($Group_store)==1)){
                /****当此团购为实物且只指定一个店铺时，将店铺id直接带入保存到订单里*************/
                $noworder['store_id']=$Group_store['0']['store_id'];//店铺id
            }
            $noworder["group_id"]=$groupnow["group_id"];
            $noworder["order_name"]=$groupnow["s_name"]."*".$value["pro_num"];//商品名字加上商品数量
            $noworder["uid"]=$this->uid;
            $noworder["mer_id"]=$groupnow["mer_id"];
        //    $noworder["store_id"]=$groupnow["store_id"];
            $noworder["num"]=$value["pro_num"];
            $noworder["price"]=$groupnow["price"];
            $noworder["total_money"]=round(floatval($value["pro_num"])*$groupnow["price"],2);
            $moneysum=round(floatval($noworder["total_money"]),2)+$moneysum;
            $noworder["contact_name"]=$addressinfo["name"];
            $noworder["phone"]=$addressinfo["phone"];
            $noworder["zipcode"]=$addressinfo["zipcode"];
            $noworder['adress']=$adrprovince.$adrcity.$adrarea.$addressinfo["adress"];
            $noworder['tuan_type']=2;
            $noworder['add_time']=time();
            $noworder['submit_order_time']=time();
            $noworder['adam_id']=$adamid;//订单随机码
            //添加失败返回false
            if(!($group_orderdata->data($noworder)->add())){
                return false;
            }
        }
        //生成购物车大订单
        if($usercardid=D("Usercardrecord")->data(array("add_time"=>time(),"uid"=>$this->uid,"totalmoney"=>empty($coupon)?$moneysum:round($moneysum-$coupon["denomination"],2)>0?round($moneysum-$coupon["denomination"],2):0.02,"adam_id"=>$adamid,"couponid"=>empty($coupon)?0:$coupon["id"]))->add()){
            return array("cardid"=>$usercardid,"totalmoney"=>empty($coupon)?$moneysum:round($moneysum-$coupon["denomination"],2)>0?round($moneysum-$coupon["denomination"],2):0.02);
        }
    }

    /**
     * 我的订单
     * 1 待付款 2等待发货 3 等待收货 4等待评价 5已完成
     */
    public function  listmyOrder(){
        $status=$_GET["status"];
        $groupcondition="`gorder`.`uid`=".$this->uid."  AND `gorder`.`sun_id` IS NULL";

        if($status==1){
            $groupcondition.=" AND `gorder`.`paid`='0' AND `gorder`.`status` < '4' ";
        }elseif($status==2){
            $groupcondition.=" AND `gorder`.`paid`='1'";
            $groupcondition .= " AND `gorder`.`user_confirm`='0' AND `gorder`.`status` = '0' ";

        }elseif($status==3){
            $groupcondition.=" AND `gorder`.`paid`='1'";
            $groupcondition .= " AND `gorder`.`user_confirm`='0' AND `gorder`.`status` = '1' ";

        }
        elseif($status==4){
            $groupcondition .= " AND `gorder`.`paid`='1'";
            $groupcondition .= " AND `gorder`.`status`='1'";
            $groupcondition .= " AND `gorder`.`user_confirm`='1'";
        }elseif($status==5){
            $groupcondition .= " AND `gorder`.`paid`='1'";
            $groupcondition .= " AND `gorder`.`status`='2'";
        }else{
            $groupcondition.=" AND `gorder`.`status`<=3";
        }
        $count2 = D('Group_order')->alias("gorder")->where($groupcondition)->count();
     //    echo D()->getLastSql();die;
        $allcount=$count2;
        //加入页码最大限制，超过最大值返回空
        $req_page=$_GET['page'];
        $max_page=ceil($allcount/15);
        if($req_page>$max_page){
            $this->returnAjax("没有更多数据了",2);
        }
        import('@.ORG.group_page');

        $p = new Page($count2, 15,"page");

        $mode=new Model();

        $sql="";
        $sql .= "SELECT godetail.*,merchant.name as merchant_name from (SELECT 2 as name, gorder.tuan_type as tuan_type,gorder.group_pass as group_pass,gorder.user_confirm,gorder.order_id, gorder.order_name, gorder.uid, gorder.mer_id, gorder.store_id,gorder.phone, gorder.num as total, gorder.express_id,gorder.express_type,(gorder.balance_pay+gorder.payment_money) as price, gorder.total_money as order_price,gorder.price as oprice, gorder.add_time as dateline, gorder.paid, gorder.status, gorder.pay_type, gorder.pay_time, gorder.third_id, gorder.group_id as order_detail_id,gorder.is_mobile_pay, gorder.balance_pay, gorder.payment_money, gorder.card_id, gorder.merchant_balance, gorder.is_pay_bill ,g.pic as order_image,g.picapp,g.picthumb FROM " . C('DB_PREFIX') . "group_order gorder LEFT JOIN ".C('DB_PREFIX') . "group g ON gorder.group_id=g.group_id WHERE ".$groupcondition.") as godetail LEFT JOIN ".C('DB_PREFIX') . "merchant merchant ON godetail.mer_id=merchant.mer_id";
        $sql .= " ORDER BY dateline DESC LIMIT {$p->firstRow}, {$p->listRows}";
        $res = $mode->query($sql);
       // echo  json_encode($res);die;
        if(empty($res)){
            if($req_page>1){
                $this->returnAjax("没有获取到数据",0);
            }else{
                $this->returnAjax("没有获取到数据",2);
            }

        }else{
          //  echo  json_encode($res);die;
            $groupimage=new group_image();
            $dataarray=array();
            foreach ($res as $key=>$value){
//                if(!empty($value["picthumb"])){
//                    $tmp_pic_arr = explode(';',$value['picthumb']);
//                }
//                elseif (!empty($value["picapp"])){
//                    $tmp_pic_arr = explode(';',$value['picapp']);
//
//                }else{
    //                $tmp_pic_arr = explode(';',$value['order_image ']);
//                }
             //   $dataarray[$key]["image"]= $groupimage->get_image_by_path($tmp_pic_arr[0])['image'];
                $dataarray[$key]["image"]=empty($value["order_image"])?"http://www.xiaonongding.com/xnd.png":$groupimage->get_image_by_path($value["order_image"],"s");
                $dataarray[$key]["merchant_name"]=$value["merchant_name"];
                $dataarray[$key]["order_name"]=$value["order_name"];
                $dataarray[$key]["order_num"]=$value["total"];
                $dataarray[$key]["total_money"]=$value["order_price"];
                $dataarray[$key]["price"]=$value["oprice"];
                $dataarray[$key]["order_id"]=$value["order_id"];
                $dataarray[$key]["group_id"]=$value["order_detail_id"];
                $dataarray[$key]["add_time"]=date("Y-m-d H:i:s",$value["dateline"]);
                $dataarray[$key]["expressname"]=empty(D('Express')->get_express($value['express_type'])["name"])?"":D('Express')->get_express($value['express_type'])["name"];
                $dataarray[$key]["expressid"]=$value["express_id"];
                if($value["paid"]==0){
                    $dataarray[$key]["statustext"]="待付款";
                    $dataarray[$key]["orderstatus"]=1;
                }elseif ($value["status"]==0){
                    $dataarray[$key]["statustext"]="待发货";
                    $dataarray[$key]["orderstatus"]=2;
                }
                elseif ($value["status"]==1){
                    if($value["user_confirm"]==0){
                        $dataarray[$key]["statustext"]="待收货";
                        $dataarray[$key]["orderstatus"]=3;
                    }else{
                        $dataarray[$key]["statustext"]="待评价";
                        $dataarray[$key]["orderstatus"]=4;
                    }

                }elseif ($value["status"]==2){
                    $dataarray[$key]["statustext"]="已完成";
                    $dataarray[$key]["orderstatus"]=5;

                }elseif($value["status"]==3){
                    $dataarray[$key]["statustext"]="已退款";
                    $dataarray[$key]["orderstatus"]=6;
                }else{
                    $dataarray[$key]["statustext"]="未知订单状态";
                    $dataarray[$key]["orderstatus"]=7;
                }


            }
            $this->returnAjax($dataarray,1);
        }



    }

    /**
     * 1 待付款 2等待发货 3 等待收货 4等待评价 5已完成
     */
    public function  listMyorder2(){
        //$records=D("Usercardrecord")->field("adam_id")->where(array("uid"=>$this->uid))->select();
        $page=empty($_GET['page'])?1:$_GET['page'];
        $status=$_GET["status"];
        $offset=($page-1)*10;
        if(!empty($status)){
          if($status==1){
              $sql="SELECT go.order_id as orderid,go.user_confirm as user_confirm,re.payment_money as payment_money,go.paid as paid,go.add_time as addtime,go.`status` as status,re.adam_id as adamid,re.record_id as recordid,re.totalmoney as totalmoney FROM pigcms_usercardrecord as re LEFT JOIN pigcms_group_order as go ON  re.adam_id=go.adam_id WHERE go.uid=".$this->uid." AND go.paid=0 AND go.status<4 GROUP BY re.adam_id  UNION ALL (SELECT god.order_id as orderid,god.user_confirm as user_confirm,god.payment_money as payment_money,god.paid as paid,god.add_time as addtime,god.`status` as status,'' as adamid,'' as recordid,god.total_money as totalmoney FROM pigcms_group_order as god WHERE god.uid=".$this->uid." AND god.adam_id = '' AND god.paid=0 AND god.status<4 ) ORDER BY addtime DESC LIMIT ".$offset.",10";
          }elseif ($status==2){
              $sql="SELECT go.order_id as orderid,go.user_confirm as user_confirm,re.payment_money as payment_money,go.paid as paid,go.add_time as addtime,go.`status` as status,re.adam_id as adamid,re.record_id as recordid,re.totalmoney as totalmoney FROM pigcms_usercardrecord as re LEFT JOIN pigcms_group_order as go ON  re.adam_id=go.adam_id WHERE go.uid=".$this->uid." AND go.paid=1 AND go.status=0 AND go.user_confirm=0 GROUP BY re.adam_id  UNION ALL (SELECT god.order_id as orderid,god.user_confirm as user_confirm,god.payment_money as payment_money,god.paid as paid,god.add_time as addtime,god.`status` as status,'' as adamid,'' as recordid,god.total_money as totalmoney FROM pigcms_group_order as god WHERE god.uid=".$this->uid." AND god.adam_id = '' AND god.paid=1 AND god.status=0 AND god.user_confirm=0 ) ORDER BY addtime DESC LIMIT ".$offset.",10";

          }elseif ($status==3){

              $sql="SELECT go.order_id as orderid,go.user_confirm as user_confirm,re.payment_money as payment_money,go.add_time as addtime,go.paid as paid,go.`status` as status,re.adam_id as adamid,re.record_id as recordid,re.totalmoney as totalmoney FROM pigcms_usercardrecord as re LEFT JOIN pigcms_group_order as go ON  re.adam_id=go.adam_id WHERE go.uid=".$this->uid." AND go.paid=1 AND go.status=1 AND go.user_confirm=0 GROUP BY re.adam_id  UNION ALL (SELECT god.order_id as orderid,god.user_confirm as user_confirm,god.payment_money as payment_money,god.paid as paid,god.add_time as addtime,god.`status` as status,'' as adamid,'' as recordid,god.total_money as totalmoney FROM pigcms_group_order as god WHERE god.uid=".$this->uid." AND god.adam_id = '' AND god.paid=1 AND god.status=1 AND god.user_confirm=0 ) ORDER BY addtime DESC LIMIT ".$offset.",10";

          }
          elseif ($status==4){
              $sql="SELECT go.order_id as orderid,go.user_confirm as user_confirm,re.payment_money as payment_money,go.add_time as addtime,go.paid as paid,go.`status` as status,re.adam_id as adamid,re.record_id as recordid,re.totalmoney as totalmoney FROM pigcms_usercardrecord as re LEFT JOIN pigcms_group_order as go ON  re.adam_id=go.adam_id WHERE go.uid=".$this->uid." AND go.paid=1 AND go.status=1 AND go.user_confirm=1 GROUP BY re.adam_id  UNION ALL (SELECT god.order_id as orderid,god.user_confirm as user_confirm,god.payment_money as payment_money,god.paid as paid,god.add_time as addtime,god.`status` as status,'' as adamid,'' as recordid,god.total_money as totalmoney FROM pigcms_group_order as god WHERE god.uid=".$this->uid." AND god.adam_id = '' AND god.paid=1 AND god.status=1 AND god.user_confirm=1 ) ORDER BY addtime DESC LIMIT ".$offset.",10";


          }elseif ($status==5){
              $sql="SELECT go.order_id as orderid,go.user_confirm as user_confirm,re.payment_money as payment_money,go.add_time as addtime,go.paid as paid,go.`status` as status,re.adam_id as adamid,re.record_id as recordid,re.totalmoney as totalmoney FROM pigcms_usercardrecord as re LEFT JOIN pigcms_group_order as go ON  re.adam_id=go.adam_id WHERE go.uid=".$this->uid." AND go.paid=1 AND go.status=2 AND go.user_confirm=1 GROUP BY re.adam_id  UNION ALL (SELECT god.order_id as orderid,god.user_confirm as user_confirm,god.payment_money as payment_money,god.add_time as addtime,god.`status` as status,'' as adamid,god.paid as paid,'' as recordid,god.total_money as totalmoney FROM pigcms_group_order as god WHERE god.uid=".$this->uid." AND god.adam_id = '' AND god.paid=1 AND god.status=2 AND god.user_confirm=1 ) ORDER BY addtime DESC LIMIT ".$offset.",10";

          }else{
              $this->returnAjax("非法请求",2);
          }
        }else{
            $sql="SELECT go.order_id as orderid,go.user_confirm as user_confirm,re.payment_money as payment_money,go.paid as paid,go.add_time as addtime,go.`status` as status,re.adam_id as adamid,re.record_id as recordid,re.totalmoney as totalmoney FROM pigcms_usercardrecord as re LEFT JOIN pigcms_group_order as go ON  re.adam_id=go.adam_id WHERE go.uid=".$this->uid." GROUP BY re.adam_id  UNION ALL (SELECT god.order_id as orderid,god.user_confirm as user_confirm,god.payment_money as payment_money,god.paid as paid,god.add_time as addtime,god.`status` as status,'' as adamid,'' as recordid,god.total_money as totalmoney FROM pigcms_group_order as god WHERE god.uid=".$this->uid." AND god.adam_id = '' ) ORDER BY addtime DESC LIMIT ".$offset.",10";
        }

       $result= M()->query($sql);
        if(empty($result)){
            $this->returnAjax("没有数据啦".D()->getLastSql(),2);
        }
       $groupdata=D("Group_order");
       $merchantdata=D("Merchant");
       $datagroup=D("Group");
           $groupimage=new group_image();
       foreach ($result as $key=>$value){
           $result[$key]["addtime"]=date("Y-m-d H:i:s",$value["addtime"]);
           if(!empty($value["adamid"])){

              $orders=$groupdata->where(array("adam_id"=>$value['adamid']))->select();
              if(count($orders)==1&&!empty($orders[0]["express_type"])){
                  $express=D("Express")->where(array("id"=>$orders[0]["express_type"]))->find();
                  $result[$key]["expresscode"]=$express['juhecode'];
              }else{
                  $result[$key]["expresscode"]="";
              }
              $realorders=array();
              $money=0;
              foreach ($orders as $k=>$v){
                  $group=$datagroup->where(array("group_id"=>$v['group_id']))->find();
                  $merchant=$merchantdata->where(array("mer_id"=>$v['mer_id']))->find();
                  $realorders[$k]["image"]=empty($group["pic"])?"http://www.xiaonongding.com/xnd.png":$groupimage->get_image_by_path($group["pic"],"s");
                  $realorders[$k]['merchant_name']=empty($merchant['name'])?"":$merchant['name'];
                  $realorders[$k]['order_name']=$v['order_name'];
                  $realorders[$k]['order_num']=$v["num"];
                  $realorders[$k]['total_money']=$v['total_money'];
                  $realorders[$k]['price']=$v['price'];
                  $realorders[$k]["order_id"]=$v['order_id'];
                  $realorders[$k]['group_id']=$v['group_id'];
                  $realorders[$k]['add_time']=date("Y-m-d H:i:s",$v['add_time']);
                  $realorders[$k]['expressname']=empty(D('Express')->get_express($v['express_type'])["name"])?"":D('Express')->get_express($v['express_type'])["name"];
                  $realorders[$k]['expressid']=$v["express_id"];
                  $money+=round($v["total_money"]+$v['balance_pay'],2);

                  if($v["paid"]==0){
                      $realorders[$k]["statustext"]="待付款";
                      $realorders[$k]["orderstatus"]=1;
                      $result[$key]["statustext"]="待付款";
                      $result[$key]["orderstatus"]=1;
                  }elseif ($v["status"]==0){
                      $realorders[$k]["statustext"]="待发货";
                      $realorders[$k]["orderstatus"]=2;
                      $result[$key]["statustext"]="待发货";
                      $result[$key]["orderstatus"]=2;
                  }
                  elseif ($v["status"]==1){
                      if($value["user_confirm"]==0){
                          $realorders[$k]["statustext"]="待收货";
                          $realorders[$k]["orderstatus"]=3;
                          $result[$key]["statustext"]="待收货";
                          $result[$key]["orderstatus"]=3;
                      }else{
                          $realorders[$k]["statustext"]="待评价";
                          $realorders[$k]["orderstatus"]=4;
                          $result[$key]["statustext"]="待评价";
                          $result[$key]["orderstatus"]=4;
                      }

                  }elseif ($v["status"]==2){
                      $realorders[$k]["statustext"]="已完成";
                      $realorders[$k]["orderstatus"]=5;
                      $result[$key]["statustext"]="已完成";
                      $result[$key]["orderstatus"]=5;

                  }elseif($v["status"]==3){
                      $realorders[$k]["statustext"]="已退款";
                      $realorders[$k]["orderstatus"]=6;
                      $result[$key]["statustext"]="已退款";
                      $result[$key]["orderstatus"]=6;
                  }else{
                      $realorders[$k]["statustext"]="未知订单状态";
                      $realorders[$k]["orderstatus"]=7;
                      $result[$key]["statustext"]="未知状态";
                      $result[$key]["orderstatus"]=7;
                  }
              }
             // echo  json_encode($realorders);die;
               $result[$key]["orders"]=$realorders;
               $result[$key]["iscard"]=1;
               if($value['paid']==1){
                   $result[$key]["payment_money"]=$money;
               }else{
                   $result[$key]["payment_money"]=0;
               }
           }else{
               $result[$key]["iscard"]=0;
               $grouporder1=$groupdata->where(array("order_id"=>$value['orderid']))->find();
               if(empty($grouporder1["express_type"])){
                   $result[$key]["expresscode"]="";
               }else{
                   $express=D("Express")->where(array("id"=>$grouporder1["express_type"]))->find();
                   $result[$key]["expresscode"]=$express["juhecode"];
               }
               $group1=$datagroup->where(array("group_id"=>$grouporder1['group_id']))->find();
               $merchant1=$merchantdata->where(array("mer_id"=>$group1['mer_id']))->find();
               $data["image"]=empty($group1["pic"])?"http://www.xiaonongding.com/xnd.png":$groupimage->get_image_by_path($group1["pic"],"s");
                $data["merchant_name"]=empty($merchant1["name"])?"":$merchant1["name"];
                $data["order_name"]=$grouporder1["order_name"];
                $data["order_num"]=$grouporder1['num'];
                $data["total_money"]=$grouporder1['total_money'];
                $data["price"]=$grouporder1['price'];
                $data['order_id']=$grouporder1['order_id'];
                $data["group_id"]=$grouporder1["group_id"];

                $data["add_time"]=$grouporder1["add_time"];
                $data["expressname"]=empty(D('Express')->get_express($grouporder1['express_type'])["name"])?"":D('Express')->get_express($grouporder1['express_type'])["name"];
                 $data["expressid"]=$grouporder1["express_id"];
               if($grouporder1["paid"]==0){
                   $data["statustext"]="待付款";
                   $data["orderstatus"]=1;
                   $result[$key]["statustext"]="待付款";
                   $result[$key]["orderstatus"]=1;
               }elseif ($grouporder1["status"]==0){
                   $data["statustext"]="待发货";
                   $data["orderstatus"]=2;
                   $result[$key]["statustext"]="待发货";
                   $result[$key]["orderstatus"]=2;
               }
               elseif ($grouporder1["status"]==1){
                   if($grouporder1["user_confirm"]==0){
                       $data["statustext"]="待收货";
                       $data["orderstatus"]=3;
                       $result[$key]["statustext"]="待收货";
                       $result[$key]["orderstatus"]=3;
                   }else{
                       $data["statustext"]="待评价";
                       $data["orderstatus"]=4;
                       $result[$key]["statustext"]="待评价";
                       $result[$key]["orderstatus"]=4;
                   }

               }elseif ($grouporder1["status"]==2){
                   $data["statustext"]="已完成";
                   $data["orderstatus"]=5;
                   $result[$key]["statustext"]="已完成";
                   $result[$key]["orderstatus"]=5;

               }elseif($grouporder1["status"]==3){
                   $data["statustext"]="已退款";
                   $data["orderstatus"]=6;
                   $result[$key]["statustext"]="已退款";
                   $result[$key]["orderstatus"]=6;
               }else{
                   $data["statustext"]="未知订单状态";
                   $data["orderstatus"]=7;
                   $result[$key]["statustext"]="未知状态";
                   $result[$key]["orderstatus"]=7;
               }

               $result[$key]["orders"][0]=$data;
           }
       }
$this->returnAjax($result,1);
    }

    /**
     * 订单详情
     */
    public function  orderdetail(){
        $order_id=intval($_GET['order_id']);
        $uid=$this->user_session['uid'];
        if(empty($uid)){
            $this->returnAjax("未获取到登录信息！",0);
        }
        if(empty($order_id)){
            $this->returnAjax("未获取到订单id!",0);
        }

        $now_order = D('Group_order')->get_order_detail_by_id($uid,$_GET['order_id']);
        if(empty($now_order)){
            $this->returnAjax("未获取到订单详情信息！",0);
        }
        $group=D("Group")->where("group_id =".$now_order["group_id"])->find();
        $merchant=D("Merchant")->where("mer_id =".$now_order["mer_id"])->find();
        //推荐分类产品
        $category_group_list = D('Group')->get_grouplist_by_catId($group["cat_id"],$group['cat_fid'],5,true);
        $puregoods=array();
        foreach($category_group_list as $key=>$value){
            if($value['group_id'] == $group['group_id']){
                unset($category_group_list[$key]);
            }
        }
        foreach ($category_group_list as $key=>$value) {
            $puregoods[$key]["id"] = $value["group_id"];
            $puregoods[$key]["image"] = $value["list_pic"];
            $puregoods[$key]["title"] = $value["group_name"];
            $puregoods[$key]["current_price"] = $value["price"];
            if((time()-intval($value["add_time"]))<3600*24*2){
                $puregoods[$key]["promotion"]=array("text"=>"新品","background"=>"");
            }else{
                $puregoods[$key]["promotion"]=array("text"=>"","background"=>"");
            }
        }

        $result["order_id"]=$now_order["order_id"];
        $result["contact_name"]=$now_order["contact_name"];
        $result["phone"]=$now_order["phone"];
        $result['adress']=$now_order["adress"];
        $result["expressname"]=empty(D('Express')->get_express($now_order['express_type'])["name"])?"":D('Express')->get_express($now_order['express_type'])["name"];
        $result["expressid"]=$now_order["express_id"];
        if($now_order["paid"]==0){
            $result["statustext"]="待付款";
            $result["orderstatus"]=1;
        }elseif ($now_order["status"]==0){
            $result["statustext"]="待发货";
            $result["orderstatus"]=2;
        }
        elseif ($now_order["status"]==1){
            if($now_order["user_confirm"]==0){
                $result["statustext"]="待收货";
                $result["orderstatus"]=3;
            }else{
                $result["statustext"]="待评价";
                $result["orderstatus"]=4;
            }

        }elseif ($now_order["status"]==2){
            $result["statustext"]="已完成";
            $result["orderstatus"]=5;

        }elseif($now_order["status"]==3){
            $result["statustext"]="已退款";
            $result["orderstatus"]=6;
        }else{
            $result["statustext"]="未知订单状态";
            $result["orderstatus"]=7;
        }
        $result["merchant_name"]=$merchant["name"];
        $result["image"]=$now_order["list_pic"];
        $result["recommend"]=$puregoods;
        $this->returnAjax($result,1);


    }


    //获取用户订单详情接口
    //根据获取的type类型判断是什么类型，然后获取具体订单详情参数
    public function getOrderDetail(){
        //type=1,为group类型订单
        //type=2,为meal类型订单
        $order_id=intval($_GET['order_id']);
        $uid=$this->user_session['uid'];
        if(empty($uid)){
            $this->returnAjax("未获取到登录信息！",0);
        }
        if(empty($order_id)){
            $this->returnAjax("未获取到订单id!",0);
        }

            $now_order = D('Group_order')->get_order_detail_by_id($uid,$_GET['order_id']);
            if(empty($now_order)){
                $this->returnAjax("未获取到订单详情信息！",0);
            }else{
              $groupimage=new group_image();
               // echo  json_encode($now_order);die;
                $result["order_id"]=$now_order["order_id"];
                $result["contact_name"]=$now_order["contact_name"];
                $result["phone"]=$now_order["phone"];
                $result["adress"]=$now_order["adress"];
                $result["mer_id"]=$now_order["mer_id"];
                $result["add_time"]=date("Y-m-d H:i:s",$now_order["add_time"]);
                $result["pay_time"]=date("Y-m-d H:i:s",$now_order["pay_time"]);
                $result["pay_type"]=$now_order["pay_type"];
                $result["express_type"]=$now_order["express_type"];
                $result["group_id"]=$now_order["group_id"];
                $result["express_id"]=$now_order["express_id"];
                $result["total_money"]=$now_order["total_money"];
                $result["expresscode"]=$now_order["express_info"]["juhecode"];
                $result["num"]=$now_order["num"];
                $result["title"]=$now_order["s_name"];
//                if(empty($now_order["picapp"])){
                    $result["image"]=$now_order['list_pic'];

//                }else{
//                    $result["image"]=$now_order['picapp'];
//
//                }
              //  $result["image"]=$images['image'];
              //  $result["image"]=$now_order["list_pic"];
                $result["payment_money"]=$now_order["payment_money"];
                $result["share_url"]="http://www.xiaonongding.com/wap.php?g=Wap&c=Group&a=detail&group_id=".$result["group_id"];
                if(!empty($result["express_type"])){
                    $express=D("Express")->where("id = ".$result["express_type"])->find();
                    $result["express_type_text"]=$express["name"];
                }else{
                    $result["express_type_text"]="";
                }
                $merchant=D("Merchant")->field("name")->where("mer_id = ".$result["mer_id"])->find();
                $result["merchant_name"]=$merchant["name"];
                if($now_order["paid"]==0){
                    $result["statustext"]="待付款";
                    $result["orderstatus"]=1;
                }elseif ($now_order["status"]==0){
                    $result["statustext"]="待发货";
                    $result["orderstatus"]=2;
                }
                elseif ($now_order["status"]==1){
                    if($now_order["user_confirm"]==0){
                        $result["statustext"]="待收货";
                        $result["orderstatus"]=3;
                    }else{
                        $result["statustext"]="待评价";
                        $result["orderstatus"]=4;
                    }

                }elseif ($now_order["status"]==2){
                    $result["statustext"]="已完成";
                    $result["orderstatus"]=5;

                }elseif($now_order["status"]==3){
                    $result["statustext"]="已退款";
                    $result["orderstatus"]=6;
                }else{
                    $result["statustext"]="未知订单状态";
                    $result["orderstatus"]=7;
                }
                if($result["orderstatus"]<3){
                    $result["express_id"]="未发货";
                    $result["express_type_text"]="未发货";
                }
                $result["coupon"]="";
                if($result["orderstatus"]>=2){
                    if(!empty($now_order["adam_id"])){

                        $usercardrecord=D("Usercardrecord")->where(array("adam_id"=>$now_order["adam_id"]))->find();
                      // echo  json_encode($usercardrecord);die;
                        if(!empty($usercardrecord)&&$usercardrecord["couponid"]>0){
                            $coupon=D("Usercoupon")->where("id =".$usercardrecord["couponid"])->find();
                            if(!empty($coupon)){
                                $result["coupon"]=$coupon["denomination"]."";
                            }
                        }

                    }
                }
                $this->returnAjax($result,1);
            }

    }

    /**
     * 取消订单 接口
     */
    public function group_order_del(){
        if(IS_POST){                            //获取订单详情方法(group_order)
            $now_order = D('Group_order')->get_order_detail_by_id($_SESSION["user"]["uid"],intval($_POST['order_id']));
            if(empty($now_order)){
                $this->returnAjax("当前订单不存在",0);
            }else if($now_order['paid']){
                $this->returnAjax('当前订单已付款，不能删除。',0);
            }
            $condition_group_order['order_id'] = $now_order['order_id'];
            $data_group_order['status'] = 4;
            if(D('Group_order')->where($condition_group_order)->data($data_group_order)->save()){
                $this->returnAjax("取消订单成功",1);
            }else{
                $this->returnAjax('删除失败！请重试。',0);
            }

        }else{
            $this->returnAjax("非法请求",0);
        }

    }
    /**
     * 取消订单 接口
     * @$order_id int 订单id
     * @$adam_id string 购物车订单标记
     */
    //
    public function new_group_order_del(){
        if(IS_POST){
            //获取订单详情
            $new_order = D('Group_order')->get_order_detail_by_id($_SESSION['user']['uid'],intval($_POST['$order_id'],$_POST['adam_id']='');

            if(empty($new_order)){
                $this->returnAjax('当前订单不存在',0);
            }else if($new_order['paid']){//付款字段
                $this->returnAjax('当前订单已付款,不能取消',0);
            }
            //如果为空的时候,则是小订单,直接取消
            if(empty($_POST['adam_id'])){
                $condition_group_order['order_id'] = $now_order['order_id'];
                $data_group_order['status'] = 4;
                if(D('Group_order')->where($condition_group_order)->data($data_group_order)->save()){
                    $this->returnAjax("取消订单成功",1);
                }else{
                    $this->returnAjax('删除失败！请重试。',0);
                }
            }
            //循环取消大订单内的订单
            foreach($new_order as $key=>$value){
                $condition_group_order['order_id']= $value['order_id'];
                $data_group_order['status'] = 4;
                if(D('Group_order')->where($condition_group_order)->data($data_group_order)->save()){
                    $this->returnAjax("取消订单成功",1);
                }else{
                    $this->returnAjax('取消失败！请重试。',0);
                }
            }

        }else{
            $this->returnAjax("非法请求",0);
        }
    }
}