document.write('<div style="display: none;">http://app.qyer.com/lastminute/</div>'+"\n");
document.write('<div class="qyer_footer">'+"\n");
document.write('	<div class="topline"></div>'+"\n");
document.write('	<div class="content">'+"\n");
document.write('		<p class="nav">'+"\n");
document.write('			<a href="http://www.qyer.com/htmlpages/about.html" target="_blank" rel="nofollow" data-bn-ipg="foot-about-1">穷游简介</a>'+"\n");
document.write('			<a href="http://www.qyer.com/partner/" target="_blank" rel="nofollow" data-bn-ipg="foot-about-3">合作伙伴</a>'+"\n");
document.write('			<a href="http://www.qyer.com/job/" target="_blank" rel="nofollow" data-bn-ipg="foot-join-1">加入我们</a>'+"\n");
document.write('			<a href="http://site.qyer.com/tyro/" target="_blank" rel="nofollow" data-bn-ipg="foot-help-1">新手上路</a>'+"\n");
document.write('			<a href="http://bbs.qyer.com/forum-10-1.html" target="_blank" rel="nofollow" data-bn-ipg="foot-help-2">使用帮助</a>'+"\n");
document.write('			<a href="http://www.qyer.com/sitemap.html" target="_blank" data-bn-ipg="foot-help-4">网站地图</a>'+"\n");
document.write('			<a href="http://www.qyer.com/htmlpages/member.html" target="_blank" rel="nofollow" data-bn-ipg="foot-clause-1">会员条款</a>'+"\n");
document.write('			<a href="http://www.qyer.com/htmlpages/bbsguide.html" target="_blank" rel="nofollow" data-bn-ipg="foot-clause-2">社区指南</a>'+"\n");
document.write('			<a href="http://www.qyer.com/htmlpages/copyright.html" target="_blank" rel="nofollow" data-bn-ipg="foot-clause-3">版权声明</a>'+"\n");
document.write('			<a href="http://www.qyer.com/htmlpages/exemption.html" target="_blank" rel="nofollow" data-bn-ipg="foot-clause-4">免责声明</a>'+"\n");
document.write('			<a href="http://www.qyer.com/htmlpages/contact.html" target="_blank" rel="nofollow" data-bn-ipg="foot-about-2">联系我们</a>'+"\n");
document.write('		</p>'+"\n");
document.write('		<p class="info">2004-2016 &copy; 穷游网&reg;  qyer.com All rights reserved. Version v5.57  京ICP备12003524号  京公网安备11010502023470  京ICP证140673号</p>'+"\n");
document.write('    '+"\n");
document.write('        <!--友情链接模块-->'+"\n");
document.write('        '+"\n");
document.write('	</div>'+"\n");
document.write('</div>'+"\n");
document.write(''+"\n");
document.write(''+"\n");
document.write('<script type="text/javascript">'+"\n");
document.write(''+"\n");
document.write('var _gaq = _gaq || [];'+"\n");
document.write(''+"\n");
document.write('_gaq.push(["_setAccount", "UA-185023-1"]);'+"\n");
document.write('_gaq.push(["_setDomainName", "qyer.com"]);'+"\n");
document.write('_gaq.push(["_setSiteSpeedSampleRate",10]);'+"\n");
document.write('_gaq.push(["_addIgnoredRef", "qyer.com"]);'+"\n");
document.write('_gaq.push(["_addOrganic","soso","w"]);'+"\n");
document.write('_gaq.push(["_addOrganic","sogou","query"]);'+"\n");
document.write('_gaq.push(["_addOrganic","baidu","word"]);'+"\n");
document.write('_gaq.push(["_addOrganic","baidu","q1"]);'+"\n");
document.write('_gaq.push(["_addOrganic","baidu","q2"]);'+"\n");
document.write('_gaq.push(["_addOrganic","m.baidu","word"]);'+"\n");
document.write('_gaq.push(["_addOrganic","so.360","q"]);'+"\n");
document.write('_gaq.push(["_addOrganic","so","q"]);'+"\n");
document.write('_gaq.push(["_addOrganic","baidu","w"]);'+"\n");
document.write('_gaq.push(["_addOrganic","cn.bing","q"]);'+"\n");
document.write('_gaq.push(["_addOrganic","sm","q"]);'+"\n");
document.write('_gaq.push(["_trackPageview"]);'+"\n");
document.write(''+"\n");
document.write('var _qyer_userid = "";'+"\n");
document.write(''+"\n");
document.write('(function() {'+"\n");
document.write('	'+"\n");
document.write('var qt = document.createElement("script"); qt.type = "text/javascript"; qt.async = true;'+"\n");
document.write(''+"\n");
document.write('qt.src = "http://qt.qyer.com/beacon.js";'+"\n");
document.write(''+"\n");
document.write('var ga = document.createElement("script"); ga.type = "text/javascript"; ga.async = true;'+"\n");
document.write(''+"\n");
document.write('//ga.src = ("https:" == document.location.protocol ? "https://ssl" : "http://www") + ".google-analytics.com/ga.js";'+"\n");
document.write('ga.src = "http://api.qyer.com/js/ga";'+"\n");
document.write(''+"\n");
document.write(''+"\n");
document.write('if("https:" == document.location.protocol){'+"\n");
document.write('    var s = document.getElementsByTagName("script")[0];s.parentNode.insertBefore(ga, s); '+"\n");
document.write('}else{'+"\n");
document.write('    var s = document.getElementsByTagName("script")[0];s.parentNode.insertBefore(qt, s); s.parentNode.insertBefore(ga, s); '+"\n");
document.write('}'+"\n");
document.write(''+"\n");
document.write('})();'+"\n");
document.write(''+"\n");
document.write('</script>'+"\n");
document.write(''+"\n");
